name: Code Scan

on:
  push:
    branches:
      - main
      - v2
  pull_request:
    branches:
      - main
      - v2
  workflow_dispatch:

jobs:
  fossa:
    name: FOSSA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.X
      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: 93622b4d45d39a92872a9593c815d7f3
          github-token: ${{ github.token }}
